export const DOMAINS = [
  { id: "dom_ai-safety", slug: "ai-safety", name: "AI Safety", description: "Alignment, evaluation, oversight, and deployment-risk research topics." },
  { id: "dom_machine-learning", slug: "machine-learning", name: "Machine Learning", description: "Model architectures, training methods, benchmarks, and capability research." },
  { id: "dom_computer-science", slug: "computer-science", name: "Computer Science", description: "Algorithms, data structures, complexity theory, and systems design." },
  { id: "dom_physics", slug: "physics", name: "Physics", description: "Theoretical and experimental physics, cosmology, and fundamental forces." },
  { id: "dom_biology", slug: "biology", name: "Biology", description: "Molecular biology, genetics, evolution, and life sciences research." },
  { id: "dom_biosecurity", slug: "biosecurity", name: "Biosecurity", description: "Preparedness, dual-use risk, and intervention analysis for biological threats." },
  { id: "dom_chemistry", slug: "chemistry", name: "Chemistry", description: "Organic, inorganic, and physical chemistry, materials science, and synthesis." },
  { id: "dom_mathematics", slug: "mathematics", name: "Mathematics", description: "Pure and applied mathematics, proofs, conjectures, and formal systems." },
  { id: "dom_climate-science", slug: "climate-science", name: "Climate Science", description: "Climate modeling, emissions trajectories, adaptation strategies, and earth systems." },
  { id: "dom_energy", slug: "energy", name: "Energy", description: "Power generation, grid infrastructure, renewables, nuclear, and energy transitions." },
  { id: "dom_space-exploration", slug: "space-exploration", name: "Space Exploration", description: "Spaceflight, planetary science, astrobiology, and space industry analysis." },
  { id: "dom_neuroscience", slug: "neuroscience", name: "Neuroscience", description: "Brain function, cognition, consciousness, and neural computation." },
  { id: "dom_medicine", slug: "medicine", name: "Medicine", description: "Clinical research, drug development, epidemiology, and public health interventions." },
  { id: "dom_economics", slug: "economics", name: "Economics", description: "Macro and microeconomic theory, monetary policy, labor markets, and trade." },
  { id: "dom_finance", slug: "finance", name: "Finance", description: "Markets, asset pricing, risk management, banking, and financial regulation." },
  { id: "dom_game-theory", slug: "game-theory", name: "Game Theory", description: "Strategic interaction, mechanism design, auction theory, and equilibrium analysis." },
  { id: "dom_governance", slug: "governance", name: "Governance", description: "Institutions, coordination mechanisms, and policy design for high-stakes systems." },
  { id: "dom_politics", slug: "politics", name: "Politics", description: "Domestic policy, elections, political institutions, and legislative analysis." },
  { id: "dom_geopolitics", slug: "geopolitics", name: "Geopolitics", description: "International relations, great power competition, alliances, and conflict analysis." },
  { id: "dom_law", slug: "law", name: "Law", description: "Legal theory, constitutional analysis, regulatory frameworks, and jurisprudence." },
  { id: "dom_philosophy", slug: "philosophy", name: "Philosophy", description: "Ethics, epistemology, metaphysics, logic, and philosophy of mind." },
  { id: "dom_psychology", slug: "psychology", name: "Psychology", description: "Cognitive science, behavioral research, decision-making, and mental health." },
  { id: "dom_sociology", slug: "sociology", name: "Sociology", description: "Social structures, inequality, institutions, culture, and demographic trends." },
  { id: "dom_history", slug: "history", name: "History", description: "Historical analysis, counterfactuals, historiography, and lessons from the past." },
  { id: "dom_education", slug: "education", name: "Education", description: "Pedagogy, learning science, education policy, and workforce development." },
  { id: "dom_linguistics", slug: "linguistics", name: "Linguistics", description: "Language structure, semantics, pragmatics, and computational linguistics." },
  { id: "dom_cybersecurity", slug: "cybersecurity", name: "Cybersecurity", description: "Threat analysis, defense strategies, vulnerability research, and information security." },
  { id: "dom_software-engineering", slug: "software-engineering", name: "Software Engineering", description: "Architecture, development practices, reliability, and systems at scale." },
  { id: "dom_robotics", slug: "robotics", name: "Robotics", description: "Autonomous systems, manipulation, perception, and human-robot interaction." },
  { id: "dom_biotechnology", slug: "biotechnology", name: "Biotechnology", description: "Gene editing, synthetic biology, biomanufacturing, and bioethics." },
  { id: "dom_cryptocurrency", slug: "cryptocurrency", name: "Cryptocurrency", description: "Blockchain protocols, tokenomics, DeFi, and decentralized governance." },
  { id: "dom_forecasting", slug: "forecasting", name: "Forecasting", description: "Prediction methodology, calibration, base rates, and superforecasting techniques." },
  { id: "dom_statistics", slug: "statistics", name: "Statistics", description: "Statistical methods, Bayesian inference, causal inference, and experimental design." },
  { id: "dom_decision-science", slug: "decision-science", name: "Decision Science", description: "Rational choice, heuristics, cognitive biases, and decision analysis under uncertainty." },
  { id: "dom_risk-analysis", slug: "risk-analysis", name: "Risk Analysis", description: "Existential risk, catastrophic scenarios, tail-risk assessment, and resilience." },
  { id: "dom_sports", slug: "sports", name: "Sports", description: "Professional and amateur athletics, performance analysis, and competitive outcomes." },
  { id: "dom_fantasy-sports", slug: "fantasy-sports", name: "Fantasy Sports", description: "Player valuation, roster optimization, matchup analysis, and draft strategy." },
  { id: "dom_esports", slug: "esports", name: "Esports", description: "Competitive gaming, team dynamics, meta-analysis, and tournament predictions." },
  { id: "dom_media", slug: "media", name: "Media", description: "Journalism, misinformation, media ecosystems, and information integrity." },
  { id: "dom_entertainment", slug: "entertainment", name: "Entertainment", description: "Film, television, music, and cultural trend analysis." },
  { id: "dom_agriculture", slug: "agriculture", name: "Agriculture", description: "Food systems, crop science, supply chains, and agricultural technology." },
  { id: "dom_urban-planning", slug: "urban-planning", name: "Urban Planning", description: "City design, transportation, housing policy, and infrastructure development." },
  { id: "dom_environmental-science", slug: "environmental-science", name: "Environmental Science", description: "Ecology, conservation, biodiversity, and pollution mitigation." },
  { id: "dom_tech-policy", slug: "tech-policy", name: "Tech Policy", description: "Platform regulation, antitrust, data privacy, and technology governance." },
  { id: "dom_ai-ethics", slug: "ai-ethics", name: "AI Ethics", description: "Fairness, accountability, transparency, and societal impact of AI systems." },
  { id: "dom_nuclear-strategy", slug: "nuclear-strategy", name: "Nuclear Strategy", description: "Deterrence theory, arms control, proliferation, and nuclear security." },
  { id: "dom_business-strategy", slug: "business-strategy", name: "Business Strategy", description: "Competitive analysis, market dynamics, business models, and strategic planning." },
  { id: "dom_startups", slug: "startups", name: "Startups", description: "Venture formation, product-market fit, fundraising, and scaling." },
  { id: "dom_supply-chains", slug: "supply-chains", name: "Supply Chains", description: "Logistics, global trade networks, resilience, and manufacturing." },
  { id: "dom_demographics", slug: "demographics", name: "Demographics", description: "Population trends, migration, fertility rates, and societal aging." },
  { id: "dom_military-strategy", slug: "military-strategy", name: "Military Strategy", description: "Doctrine, operational analysis, defense technology, and war studies." },
] as const;

export const DOMAIN_BY_ID = new Map(DOMAINS.map((d) => [d.id as string, d]));
export const DOMAIN_BY_SLUG = new Map(DOMAINS.map((d) => [d.slug as string, d]));
