import {
  LAUNCH_CORE_SCHEMA_SQL,
  PHASE2_INTEGRITY_SQL,
  PHASE3_ALIGNMENT_SQL,
  PHASE8_ADMIN_SUITE_SQL,
  PHASE6_AUTH_SQL,
  PHASE7_EXTERNAL_OAUTH_SQL,
  PHASE9_EPISTEMIC_CORE_SQL,
  PHASE10_TOPIC_FORMATS_SQL,
  PHASE11_ADAPTIVE_SCORING_SQL,
  PHASE12_PLATFORM_ANALYTICS_SQL,
  PHASE13_TOPIC_VIEW_REPUTATION_HISTORY_VOTE_TIMING_SQL,
  PHASE14_TOPIC_MEMBER_DROP_TRACKING_SQL,
  PHASE15_TOPIC_CANDIDATES_SQL,
  PHASE16_ACCOUNT_CLASSES_TOPIC_SOURCES_SQL,
  PHASE17_STANCE_AND_VERDICTS_SQL,
  PHASE18_BEHAVIORAL_AND_TRUST_SQL,
  PHASE19_ROUND_INSTRUCTION_OVERRIDES_SQL,
  PHASE20_VOTE_CATEGORIES_SQL,
  PHASE21_DOSSIER_CORE_SQL,
  PHASE22_AUTONOMOUS_ROLLING_SQL,
  PHASE23_DOMAIN_GROUPS_SQL,
  PHASE24_RENAME_DEBATE_V2_SQL,
  PHASE25_BEING_PERSONA_FIELDS_SQL,
  PHASE26_CONTRIBUTION_MODEL_PROVENANCE_SQL,
  PHASE25_DEBATE_SESSIONS_SQL,
  PHASE27_VERTICAL_REFINEMENT_SQL,
  PHASE28_REFINEMENT_CLAIMS_SQL,
  PHASE29_KNOWLEDGE_GRAPH_SQL,
  PHASE30_REFINEMENT_DEDUP_MERGED_CLAIMS_SQL,
} from "./schema.generated.js";

export {
  LAUNCH_CORE_SCHEMA_SQL,
  PHASE2_INTEGRITY_SQL,
  PHASE3_ALIGNMENT_SQL,
  PHASE8_ADMIN_SUITE_SQL,
  PHASE6_AUTH_SQL,
  PHASE7_EXTERNAL_OAUTH_SQL,
  PHASE9_EPISTEMIC_CORE_SQL,
  PHASE10_TOPIC_FORMATS_SQL,
  PHASE11_ADAPTIVE_SCORING_SQL,
  PHASE12_PLATFORM_ANALYTICS_SQL,
  PHASE13_TOPIC_VIEW_REPUTATION_HISTORY_VOTE_TIMING_SQL,
  PHASE14_TOPIC_MEMBER_DROP_TRACKING_SQL,
  PHASE15_TOPIC_CANDIDATES_SQL,
  PHASE16_ACCOUNT_CLASSES_TOPIC_SOURCES_SQL,
  PHASE17_STANCE_AND_VERDICTS_SQL,
  PHASE18_BEHAVIORAL_AND_TRUST_SQL,
  PHASE19_ROUND_INSTRUCTION_OVERRIDES_SQL,
  PHASE20_VOTE_CATEGORIES_SQL,
  PHASE21_DOSSIER_CORE_SQL,
  PHASE22_AUTONOMOUS_ROLLING_SQL,
  PHASE23_DOMAIN_GROUPS_SQL,
  PHASE24_RENAME_DEBATE_V2_SQL,
  PHASE25_BEING_PERSONA_FIELDS_SQL,
  PHASE26_CONTRIBUTION_MODEL_PROVENANCE_SQL,
  PHASE25_DEBATE_SESSIONS_SQL,
  PHASE27_VERTICAL_REFINEMENT_SQL,
  PHASE28_REFINEMENT_CLAIMS_SQL,
  PHASE29_KNOWLEDGE_GRAPH_SQL,
  PHASE30_REFINEMENT_DEDUP_MERGED_CLAIMS_SQL,
};

export const API_MIGRATIONS = [
  { tag: "001_launch_core", fileName: "001_launch_core.sql", sql: LAUNCH_CORE_SCHEMA_SQL },
  { tag: "002_phase2_integrity", fileName: "002_phase2_integrity.sql", sql: PHASE2_INTEGRITY_SQL },
  { tag: "003_phase3_alignment", fileName: "003_phase3_alignment.sql", sql: PHASE3_ALIGNMENT_SQL },
  { tag: "004_phase6_auth", fileName: "004_phase6_auth.sql", sql: PHASE6_AUTH_SQL },
  { tag: "005_phase7_external_oauth", fileName: "005_phase7_external_oauth.sql", sql: PHASE7_EXTERNAL_OAUTH_SQL },
  { tag: "006_admin_suite", fileName: "006_admin_suite.sql", sql: PHASE8_ADMIN_SUITE_SQL },
  { tag: "007_epistemic_core", fileName: "007_epistemic_core.sql", sql: PHASE9_EPISTEMIC_CORE_SQL },
  { tag: "008_topic_formats", fileName: "008_topic_formats.sql", sql: PHASE10_TOPIC_FORMATS_SQL },
  { tag: "009_adaptive_scoring", fileName: "009_adaptive_scoring.sql", sql: PHASE11_ADAPTIVE_SCORING_SQL },
  { tag: "010_platform_analytics", fileName: "010_platform_analytics.sql", sql: PHASE12_PLATFORM_ANALYTICS_SQL },
  {
    tag: "011_topic_view_reputation_history_vote_timing",
    fileName: "011_topic_view_reputation_history_vote_timing.sql",
    sql: PHASE13_TOPIC_VIEW_REPUTATION_HISTORY_VOTE_TIMING_SQL,
  },
  {
    tag: "012_topic_member_drop_tracking",
    fileName: "012_topic_member_drop_tracking.sql",
    sql: PHASE14_TOPIC_MEMBER_DROP_TRACKING_SQL,
  },
  {
    tag: "013_topic_candidates",
    fileName: "013_topic_candidates.sql",
    sql: PHASE15_TOPIC_CANDIDATES_SQL,
  },
  {
    tag: "014_account_classes_topic_sources",
    fileName: "014_account_classes_topic_sources.sql",
    sql: PHASE16_ACCOUNT_CLASSES_TOPIC_SOURCES_SQL,
  },
  {
    tag: "015_stance_and_verdicts",
    fileName: "015_stance_and_verdicts.sql",
    sql: PHASE17_STANCE_AND_VERDICTS_SQL,
  },
  {
    tag: "016_behavioral_and_trust",
    fileName: "016_behavioral_and_trust.sql",
    sql: PHASE18_BEHAVIORAL_AND_TRUST_SQL,
  },
  {
    tag: "017_round_instruction_overrides",
    fileName: "017_round_instruction_overrides.sql",
    sql: PHASE19_ROUND_INSTRUCTION_OVERRIDES_SQL,
  },
  {
    tag: "018_vote_categories",
    fileName: "018_vote_categories.sql",
    sql: PHASE20_VOTE_CATEGORIES_SQL,
  },
  {
    tag: "019_dossier_core",
    fileName: "019_dossier_core.sql",
    sql: PHASE21_DOSSIER_CORE_SQL,
  },
  {
    tag: "020_autonomous_rolling",
    fileName: "020_autonomous_rolling.sql",
    sql: PHASE22_AUTONOMOUS_ROLLING_SQL,
  },
  {
    tag: "021_domain_groups",
    fileName: "021_domain_groups.sql",
    sql: PHASE23_DOMAIN_GROUPS_SQL,
  },
  {
    tag: "022_rename_debate_v2",
    fileName: "022_rename_debate_v2.sql",
    sql: PHASE24_RENAME_DEBATE_V2_SQL,
  },
  {
    tag: "023_being_persona_fields",
    fileName: "023_being_persona_fields.sql",
    sql: PHASE25_BEING_PERSONA_FIELDS_SQL,
  },
  {
    tag: "024_contribution_model_provenance",
    fileName: "024_contribution_model_provenance.sql",
    sql: PHASE26_CONTRIBUTION_MODEL_PROVENANCE_SQL,
  },
  {
    tag: "025_debate_sessions",
    fileName: "025_debate_sessions.sql",
    sql: PHASE25_DEBATE_SESSIONS_SQL,
  },
  {
    tag: "027_vertical_refinement",
    fileName: "027_vertical_refinement.sql",
    sql: PHASE27_VERTICAL_REFINEMENT_SQL,
  },
  {
    tag: "028_refinement_claims",
    fileName: "028_refinement_claims.sql",
    sql: PHASE28_REFINEMENT_CLAIMS_SQL,
  },
  {
    tag: "029_knowledge_graph",
    fileName: "029_knowledge_graph.sql",
    sql: PHASE29_KNOWLEDGE_GRAPH_SQL,
  },
  {
    tag: "030_refinement_dedup_merged_claims",
    fileName: "030_refinement_dedup_merged_claims.sql",
    sql: PHASE30_REFINEMENT_DEDUP_MERGED_CLAIMS_SQL,
  },
] as const;
